#!/bin/zsh

# VI

VUNDLE=$HOME/.vim/bundle/Vundle.vim 
JEDI=$HOME/.vim/bundle/jedi-vim

if [[ ! -d $HOME/.vim/bundle/Vundle.vim ]]
then
	git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE
else
	cd $VUNDLE
	git pull
	cd -
fi

if [[ ! -a $HOME/.vimrc ]]
then
	ln -s $(pwd)/vim/vimrc $HOME/.vimrc
fi

cd $VUNDLE
git submodule update --init
cd -

vim +PluginInstall +qall

# ZSH

if [[ ! -a $HOME/.zshenv ]]
then
	ln -s $(pwd)/zsh/zshenv $HOME/.zshenv
	source $HOME/.zshenv
fi

if [[ ! -a $HOME/.zshrc ]]
then
	ln -s $(pwd)/zsh/zshrc $HOME/.zshrc
	source $HOME/.zshrc
fi
