#!/bin/zsh

# VI
VI_HOME=$HOME/.vim
VUNDLE=$VI_HOME/bundle/Vundle.vim 
JEDI=$VI_HOME/.vim/bundle/jedi-vim

if [[ ! -d $HOME/.vim/bundle/Vundle.vim ]]
then
	git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE
else
	cd $VUNDLE
	git pull
	cd -
fi

if [[ ! -a $HOME/.vimrc ]]
then
	ln -s $(pwd)/vim/vimrc $HOME/.vimrc
fi

if [[ ! -d $VI_HOME/ftplugin ]]
then
	ln -s $(pwd)/vim/ftplugin $VI_HOME/ftplugin
fi

if [[ ! -d $VI_HOME/plugin ]]
then
	ln -s $(pwd)/vim/plugin $VI_HOME/plugin
fi

cd $VUNDLE
git submodule update --init
cd -

vim +PluginInstall +qall

# ZSH

if [[ ! -d $HOME/.antigen ]]
then
	git clone git@github.com:zsh-users/antigen.git $HOME/.antigen
else
	cd $HOME/.antigen
	git pull
	cd -
fi

if [[ ! -a $HOME/.zshenv ]]
then
	ln -s $(pwd)/zsh/zshenv $HOME/.zshenv
	source $HOME/.zshenv
fi

if [[ ! -a $HOME/.zshrc ]]
then
	ln -s $(pwd)/zsh/zshrc $HOME/.zshrc
	source $HOME/.zshrc
fi

if [[ ! -a $HOME/.zsh/plugins ]]
then
	ln -s $(pwd)/zsh/plugins $HOME/.zsh/plugins
fi

if [[ ! -d $HOME/.zsh/completion ]]
then
	mkdir -p $HOME/.zsh/
	ln -s $(pwd)/zsh/completion $HOME/.zsh/
fi


# VIRTUALENVWRAPPER

if [[ -n "$WORKON_HOME" ]]
then
	rm $WORKON_HOME/postactivate
	ln -s $(pwd)/virtualenvwrapper/postactivate $WORKON_HOME/postactivate
	rm $WORKON_HOME/postdeactivate
	ln -s $(pwd)/virtualenvwrapper/postdeactivate $WORKON_HOME/postdeactivate
fi

# VSCODE
#
if [[ -n "$HOME/.config/Code" ]]
then
	rm $HOME/.config/Code/User/settings.json
	ln -s $(pwd)/User/settings.json "$HOME/.config/Code/User/settings.json"
	rm -r $HOME/.config/Code/Workspaces
	ln -s $(pwd)/Workspaces "$HOME/.config/Code/Workspaces"
fi

# SDKMAN - ALL

source $HOME/.zshrc

sdk install java 9.0.4-oracle
sdk default java 9.0.4-oracle
sdk install groovy 2.4.13
sdk install maven 3.5.2
sdk install gradle 4.5.1
sdk install kotlin 1.2.21
sdk install springboot 1.5.10.RELEASE

ln -s $SDKMAN_DIR/candidates/springboot/current/shell-completion/zsh/_spring $(pwd)/zsh/completion/_spring

source $HOME/.zshrc
