
# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

if [[ $(minikube status | grep Running ) ]]
then
	export MIP=$(minikube ip)
fi

# active les commentaires dans la ligne de commande
setopt interactivecomments
# active les globs etendus 
setopt extendedglob
# active la gestion des range
setopt braceccl
# active les messages d'erreur sur les variables on déclarées
# setopt nounset
# récupère les exos
# udpate-exos () {
#     pushd ~
#     curl ramirez/e/training/unix/exos.tgz | gzip -d | tar x
#     popd
# }

# Debian bug resolved
DEBIAN_PREVENT_KEYBOARD_CHANGES=yes
skip_global_compinit=1

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export ZDOTDIR="${ZDOTDIR:=$XDG_CONFIG_HOME/zsh}"
