# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history


# zstyle ':completion:*' auto-description 'specify: %d'
# zstyle ':completion:*' completer _expand _complete # _correct _approximate
# zstyle ':completion:*' format 'Completing %d'
# zstyle ':completion:*' group-name ''
# zstyle ':completion:*' menu select=2
# eval "$(dircolors -b)"
# zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' list-colors ''
# zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
# zstyle ':completion:*' menu select=long
# zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
# zstyle ':completion:*' use-compctl false
# zstyle ':completion:*' verbose true
# zstyle ':completion:*:descriptions' format "%B%d%b"

# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
# zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


# custom completion scripts
# fpath=($HOME/.zsh/completion $fpath)

# gestion simple de tmux

t () {
    (( $+1 )) ||
        { tmux ls -F '#S'; return }
    shush tmux att -t $1 ||
        tmux new -s $1
}

# active la ligne de commande en mode VI
# bindkey -v


unsetopt nounset

# export PATH="$PATH:/home/arnaud/.guix-profile/bin"

# source $HOME/.antigen/antigen.zsh

# antigen
# antigen use oh-my-zsh

# plug-ins
# default repo (oh-my-zsh)
# antigen bundle pip
# antigen bundle command-not-found
# antigen bundle git
# antigen bundle kubectl
# antigen bundle ng
# antigen bundle tonyseek/oh-my-zsh-virtualenv-prompt
# antigen theme tonyseek/oh-my-zsh-seeker-theme

# completion
# antigen bundle lukechilds/zsh-better-npm-completion
# antigen bundle zsh-users/zsh-completions

# others
# antigen bundle zsh-users/zsh-syntax-highlighting

# local plugins
# antigen bundle "$HOME/.zsh/plugins/docker" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/oracle" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/beets" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/chouffe" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/todo" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/sdkman" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/k8s" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/java" --no-local-clone
# antigen bundle "$HOME/.zsh/plugins/poetry" --no-local-clone

# load plugins
# antigen apply

# Use modern completion system
# autoload -Uz compinit && compinit -i

# virtualenvwrapper
# export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
# export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
# export WORKON_HOME=$HOME/.virtualenvs
# source /usr/local/bin/virtualenvwrapper.sh

# export ONE_XMLRPC="https://one.unistra.fr:2633/RPC2"
# export GITLAB_TOKEN='94nu-uHjjzVXeTAPj85B'

# todo binaries
# doc https://github.com/asb/sh-todo
# export PATH="$PATH:$HOME/.libs/sh-todo"
# my todo
# me

# minikube
# export MIP=$(minikube ip)

# kubectl
# source <(kubectl completion zsh)

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="/home/agrausem/.sdkman"
# [[ -s "/home/agrausem/.sdkman/bin/sdkman-init.sh" ]] && source "/home/agrausem/.sdkman/bin/sdkman-init.sh"
# prompt adam1
# export PATH="$PATH:$HOME/.yarn/bin:$HOME/.yarn/bin/bin:$HOME/.local/bin:/snap/bin"

# export PYTHONPATH="$PYTHONPATH:$HOME/.local/python/libs"

# NVM
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# export PATH="$HOME/.poetry/bin:$PATH"

# source "$HOME/.zsh/virtualenv-auto-activate.sh"
# export PATH="$HOME/.krew/bin:$PATH"

google_drive () {
	google-drive-ocamlfuse ~/Documents/GoogleDrive
}
